[SYSTEM]
timezone = Asia/Seoul
log_name = system_server
log_level = debug
log_format = %(asctime)s [%(process)d] [%(levelname)-5s] %(module)s.%(funcName)s() L%(lineno)d:: %(message)s
log_dir = /Users/hanati/workspace/agent/logs
log_filename = system.log
is_stream = true
is_file = true
is_pipe = false
is_lotate = true
topic = workflow_log
kafka_bootstrap_servers = localhost:9092
kafka_group_id = engine
log_maxsize = 104857600
backup_count = 10

[WORKFLOW]
timezone = Asia/Seoul
log_name = workflow_engine
log_level = debug
log_format = %(asctime)s [%(process)d] [%(levelname)-5s] %(module)s.%(funcName)s() L%(lineno)d:: %(message)s
log_dir = /Users/hanati/workspace/agent/logs
log_filename = workflow.log
is_stream = true
is_file = true
is_pipe = false
is_lotate = true
topic = workflow_log
kafka_bootstrap_servers = localhost:9092
kafka_group_id = engine
log_maxsize = 104857600
backup_count = 10

[ADAPTER]
timezone = Asia/Seoul
log_name = dtm_adapter
log_level = debug
log_format = %(asctime)s [%(process)d] [%(levelname)-5s] %(module)s.%(funcName)s() L%(lineno)d:: %(message)s
log_dir = /Users/hanati/workspace/agent/logs
log_filename = adapter.log
is_stream = true
is_file = true
is_pipe = false
is_lotate = true
topic = workflow_log
kafka_bootstrap_servers = localhost:9092
kafka_group_id = engine
log_maxsize = 104857600
backup_count = 10
