[SYSTEM]
timezone = Asia/Seoul
log_name = workflow_engine
log_level = info
log_format = %(asctime)s [%(process)d] [%(levelname)-5s] %(module)s.%(funcName)s() L%(lineno)d:: %(message)s
log_dir = /Users/hanati/workspace/agent/logs
log_filename = system.log
is_stream = true
is_file = true
is_pipe = true
is_lotate = true
topic = test
kafka_bootstrap_servers = 10.0.0.10:18888,10.0.0.20:18888
log_maxsize = 1048576
backup_count = 10
