[ENV]
mode = test
app_id = WORKFLOW

[HOME]
home_dir = /Users/hanati/workspace/agent
lock_dir = /Users/hanati/workspace/agent/lock

[LAUNCHER]
reload = false
access_type = file
route_dir = /Users/hanati/workspace/agent/meta
route_file = api_routes.json
active_apis = EngineAdapter,WorkflowEngine

[REMOTEPOOL]
ip = 127.0.0.1
port = 6379
password =
ttl = 0

[SERVER]
bind = 0.0.0.0:8080
workers = 1
worker_class = uvicorn.workers.UvicornWorker
timeout = 86400
keepalive = 60
worker_connections = 10000
max_requests = 5000
max_requests_jitter = 300

[ENGINE]
base_url = http://127.0.0.1:8080/