[WORKFLOW]
# access_pool_type = 'remote' or 'file' or 'db', remote: redis, file: as 'DAG' section
access_pool_type = remote
auto_load = true
reload = false
num_of_backup_metas = 20

[STORE_POOL]
# data store pool types = 'remote' as Redis or 'local' as memory
meta_pool_type = remote
remote_meta_db = 1
data_io_pool_type = remote
remote_data_io_db = 2
task_pool_type = remote
remote_task__db = 3

[ACTIVE_WORKFLOW]
workflow_id = DTM3_WF_003_RES

[RECIPE]
dir_path = /Users/hanati/workspace/agent/recipe
file_name = dtm3_v3_res.json

[WORKFLOW_TIMEOUT]
max_retries = 1
timeout = 7200
delay_time = 0.0
exponential_backoff = True

[WORKFLOW_REMOTEPOOL]
ip = 127.0.0.1
port = 6379
password=
ttl = 0

